package com.workflowmanager.engine.domain;

public enum EventType {
    WORKFLOW_SUBMITTED,
    TASK_DISPATCHED,
    TASK_READY,
    TASK_SUCCEEDED,
    TASK_RETRY_SCHEDULED,
    TASK_LEASE_EXPIRED,
    TASK_TIMED_OUT,
    TASK_FAILED,
    TASK_DEAD_LETTERED,
    TASK_REDRIVEN,
    WORKFLOW_SUCCEEDED,
    WORKFLOW_FAILED
}
